FROM node:24-alpine AS build
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
RUN npm run build -- --configuration production

FROM nginxinc/nginx-unprivileged:1.31.6-alpine3.24
COPY nginx.production.conf /etc/nginx/conf.d/default.conf
COPY --from=build --chown=101:101 /app/dist/frontend/browser /usr/share/nginx/html
USER 101:101
EXPOSE 8080
